update topology link
pingcap/docs-dm pull request #307
Opened 2020-08-28 03:48 UTC by glkappe

https://github.com/pingcap/tiup/blob/master/examples/topology.dm.example.yaml
change to：
https://github.com/pingcap/tiup/blob/master/examples/dm/topology.example.yaml

### What is changed, added or deleted? (Required)

### Which DM version(s) do your changes apply to? (Required)

- [ ] master (the latest development version, including v3.0 changes)
- [ ] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts after cherry-picked

2020-08-28 03:51 UTC, csuzhangxc reviewed
LGTM

2020-08-28 03:51 UTC, csuzhangxc commented
@TomShawn PTAL

2020-08-28 03:53 UTC, ireneontheway approved these changes
LGTM @TomShawn

2020-08-28 05:02 UTC, TomShawn commented on zh/maintain-dm-using-tiup.md
> +- 根据 ansible 部署的集群生成一个 TiUP 部署使用的拓扑文件 [topology.yml](https://github.com/pingcap/tiup/blob/master/examples/dm/topology.example.yaml)。
```suggestion
- 根据 DM-Ansible 部署的集群生成一个拓扑文件 [topology.yml](https://github.com/pingcap/tiup/blob/master/examples/dm/topology.example.yaml) 用于 TiUP 部署。
```

2020-08-28 05:05 UTC, TomShawn requested changes

2020-08-28 05:05 UTC, TomShawn commented on zh/maintain-dm-using-tiup.md
>  - 确认部署后使用生成的拓扑文件部署 2.0 以上版本的集群。
```suggestion
- 确认拓扑文件生成后，使用该文件部署 2.0 以上版本的集群。
```

2020-08-28 05:16 UTC, csuzhangxc commented on zh/maintain-dm-using-tiup.md
>  - 确认部署后使用生成的拓扑文件部署 2.0 以上版本的集群。
要不换成 `确认部署后，使用生成的拓扑文件部署`？

2020-08-31 05:54 UTC, yikeke commented on zh/maintain-dm-using-tiup.md
>  - 确认部署后使用生成的拓扑文件部署 2.0 以上版本的集群。
这个「确认部署」确认的是谁的部署，可以直接去掉吗？
```suggestion
- 使用生成的拓扑文件部署 2.0 以上版本的集群。
```

2020-08-31 09:46 UTC, csuzhangxc commented on zh/maintain-dm-using-tiup.md
>  - 确认部署后使用生成的拓扑文件部署 2.0 以上版本的集群。
其实是 `确认生成的部署拓扑文件`

2020-08-31 09:59 UTC, yikeke commented on zh/maintain-dm-using-tiup.md
>  - 确认部署后使用生成的拓扑文件部署 2.0 以上版本的集群。
```suggestion
- 确认该生成的部署拓扑文件无误后，使用该文件部署 2.0 以上版本的集群。
```
这样？

2020-08-31 10:00 UTC, csuzhangxc commented on zh/maintain-dm-using-tiup.md
>  - 确认部署后使用生成的拓扑文件部署 2.0 以上版本的集群。
LGTM

2020-08-31 10:01 UTC, yikeke approved these changes
LGTM

2020-08-31 10:02 UTC, TomShawn approved these changes
LGTM

2020-08-31 10:03 UTC, yikeke commented
/merge

2020-08-31 10:05 UTC, merged