Update deploy-a-dm-cluster-using-tiup.md
pingcap/docs-dm pull request #319
Opened 2020-08-31 06:09 UTC by lucklove

### What is changed, added or deleted? (Required)

### Which DM version(s) do your changes apply to? (Required)

- [ ] master (the latest development version, including v3.0 changes)
- [ ] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Have version specific changes 
- [ ] Might cause conflicts after cherry-picked

2020-08-31 06:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/pingcap/docs-dm?pullRequest=319) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/pingcap/docs-dm?pullRequest=319) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/pingcap/docs-dm?pullRequest=319) it.</sub>

2020-08-31 06:10 UTC, csuzhangxc reviewed
LGTM

2020-08-31 06:13 UTC, lucklove commented
I'll pack this with other experimental features

2020-08-31 06:30 UTC, lilin90 reviewed
Would you please also update the corresponding English file in this PR? Thanks!

2020-08-31 09:12 UTC, yikeke requested changes

2020-08-31 09:12 UTC, yikeke commented on zh/deploy-a-dm-cluster-using-tiup.md
> +title: 使用 TiUP 部署 DM 集群（实验特性）
1. 下面一级标题后面也加上 （实验特性）吧，只在 meta 里加的话，在官网是显示不出来的
2. 一般如果要强调是实验特性的话，会在一级标题后头加一个警告 note，说明本文描述特性仍为实验特性，不建议在生产环境下部署（告诉用户实验特性意味着什么）

2020-09-07 02:59 UTC, yikeke approved these changes
LGTM

2020-09-07 02:59 UTC, yikeke commented
/merge

2020-09-07 03:03 UTC, merged