[WIP] refine feature-online-ddl.md
pingcap/docs-dm pull request #784
Opened 2021-09-26 03:31 UTC by lance6716

### What is changed, added, or deleted? (Required)

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [x] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from:
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-09-26 03:50 UTC, lance6716 commented
/cc @sunzhaoyang @okJiang

2021-09-26 04:08 UTC, okJiang requested changes

2021-09-26 04:08 UTC, okJiang commented on zh/feature-online-ddl.md
> +- 需要将 online-ddl 工具产生的各种临时表添加到任务配置白名单中
```suggestion
- 如果任务配置文件中 `do-tables` 不为空，则需要将 online-ddl 工具产生的各种临时表添加到任务配置白名单中
```

2021-09-26 04:08 UTC, okJiang commented on zh/feature-online-ddl.md
> +- 与分库分表合并场景不兼容
为什么不兼容呢？

2021-09-26 04:11 UTC, lance6716 commented on zh/feature-online-ddl.md
> +- 与分库分表合并场景不兼容
分表的话，RENAME tbl1_gho TO tbl、RENAME tbl2_gho TO tbl 这种 DDL，只能有一个分表的 gho 表晋升成下游的合表

2021-09-26 04:12 UTC, lance6716 commented on zh/feature-online-ddl.md
> +- 受目前 DM 实现限制，在向下游应用 DDL 时，该同步任务的其他 DML 会被阻塞直到 DDL 完成。我们会在后续优化该限制
TiDB 的 DDL 其实不会阻塞 DML，所以 DM 未来可以优化成那样。

2021-09-26 04:13 UTC, lance6716 commented on zh/feature-online-ddl.md
> +- 需要将 online-ddl 工具产生的各种临时表添加到任务配置白名单中
啥意思，为空的话也要添加吧。如果你是隐含了“库级别的白名单”的意思，我觉得原始表达更简洁

2021-09-26 04:16 UTC, okJiang commented on zh/feature-online-ddl.md
> +- 需要将 online-ddl 工具产生的各种临时表添加到任务配置白名单中
因为 `do-tables` 是在不为空的时候才生效的，如果 `do-tables` 为空，则表示所有的 table 都是白名单，这种情况下不需要设置临时表为 `do-tables`

2021-09-26 04:17 UTC, okJiang commented on zh/feature-online-ddl.md
> +- 受目前 DM 实现限制，在向下游应用 DDL 时，该同步任务的其他 DML 会被阻塞直到 DDL 完成。我们会在后续优化该限制
我的理解是 DM 现在会对所有的 ddl 都阻塞，而不只是 online-ddl 场景下

2021-09-26 04:19 UTC, okJiang commented on zh/feature-online-ddl.md
> +- 与分库分表合并场景不兼容
你说的是上游 mysql 自行进行的分库分表合并场景吗？我理解成了 DM 分库分表合并。是我理解错了吗？

2021-09-26 04:20 UTC, lance6716 commented on zh/feature-online-ddl.md
> +- 与分库分表合并场景不兼容
tbl 是 route 之后的下游表名。是 DM 分库分表合并

2021-09-26 05:27 UTC, sunzhaoyang commented on zh/feature-online-ddl.md
> +因此，用户往往会选择 online DDL 工具执行 DDL，把对读写的影响降到最低。常见的 online DDL 工具有 gh-ost、pt-osc。
```suggestion
因此，用户往往会选择 online DDL 工具执行 DDL，把对读写的影响降到最低。常见的 online DDL 工具有 [gh-ost](https://github.com/github/gh-ost)、[pt-osc](https://www.percona.com/doc/percona-toolkit/3.0/pt-online-schema-change.html)。
```

2021-09-27 02:17 UTC, lance6716 commented
replaced by #786

2021-09-27 02:17 UTC, closed without merging