en: add OpenAPI docs
pingcap/docs-dm pull request #822
Opened 2021-11-08 12:21 UTC by Liuxiaozhen12

### First-time contributors' checklist 

- [x] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-dm) that's required for repo owners to accept my contribution.

### What is changed, added, or deleted? (Required)

### Which DM version(s) do your changes apply to? (Required)

- [x] master (the latest development version)
- [ ] v2.0 (TiDB DM 2.0 versions)
- [ ] v1.0 (TiDB DM 1.0 versions)

### What is the related PR or file link(s)?

- This PR is translated from: https://github.com/pingcap/docs-dm/pull/812
- Other reference link(s):

### Do your changes match any of the following descriptions?

- [ ] Delete files
- [ ] Change aliases
- [ ] Need modification after applied to another branch 
- [ ] Might cause conflicts after applied to another branch

2021-11-09 00:17 UTC, Ehco1996 commented on en/open-api.md
> +* [Get the status information of a DM-master node](#get-the-status-information-of-a-dm-master-node)
```suggestion
* [Get the node information of a DM-master node](#get-the-status-information-of-a-dm-master-node)
```

it's some node infomation of dm-master, such as ip addr, peer port, so i think use status is not accuracy

2021-11-09 00:17 UTC, Ehco1996 commented on en/open-api.md
> +* [Get the status information of a DM-master node](#get-the-status-information-of-a-dm-master-node)
please also change the dm-worker part

2021-11-09 00:17 UTC, Ehco1996 commented on en/open-api.md
> +* [Start the relay-log feature for a data source](#start-the-relay-log-feature-for-a-data-source)
```suggestion
* [Start the relay-log feature for data sources](#start-the-relay-log-feature-for-a-data-source)
```
in api we can operate relay log feature for many sources not only a source, stop/pause/resume is also the same way

2021-11-09 00:17 UTC, Ehco1996 commented on en/open-api.md
> +[experimental-features]
```suggestion
[experimental]
```
sorry aobot this change, after internal discussions, we choose use `experimental` instead of `experimental-features`, and i forget update the pr...

please also update this part in docs-cn 😘 😘 😘

2021-11-09 00:17 UTC, Ehco1996 commented on en/open-api.md
> +> - DM provides the [specification document](https://github.com/pingcap/ticdc/blob/master/dm/openapi/spec/dm.yaml) that meets OpenAPI 3.0.0 standard. This document contains all the request parameters
```suggestion
> - DM provides the [specification document](https://github.com/pingcap/ticdc/blob/master/dm/openapi/spec/dm.yaml) that meets OpenAPI 3.0.0 standard. This document contains all the request parameters and returned values and you can copy the document yaml and preview it in [Swagger Editor](https://editor.swagger.io/).
```

2021-11-09 03:00 UTC, Liuxiaozhen12 commented on en/open-api.md
> +* [Get the status information of a DM-master node](#get-the-status-information-of-a-dm-master-node)
how about just delete the `status`? Because there is already a `node` in the end.

2021-11-09 03:06 UTC, Ehco1996 commented on en/open-api.md
> +* [Get the status information of a DM-master node](#get-the-status-information-of-a-dm-master-node)
lgtm

2021-11-09 03:15 UTC, Liuxiaozhen12 commented on en/open-api.md
> +* [Start the relay-log feature for a data source](#start-the-relay-log-feature-for-a-data-source)
fixed in https://github.com/pingcap/docs-dm/pull/822/commits/a01e78f829350679ef0ee06cd94365a510db14a5. PTAL~

2021-11-09 03:16 UTC, Liuxiaozhen12 commented on en/open-api.md
> +* [Get the status information of a DM-master node](#get-the-status-information-of-a-dm-master-node)
fixed in https://github.com/pingcap/docs-dm/pull/822/commits/d436951ad44f24f29550c62f70e7b67e77f6373a.

2021-11-09 03:17 UTC, Liuxiaozhen12 commented on en/open-api.md
> +[experimental-features]
ditto~

2021-11-09 03:59 UTC, Ehco1996 approved these changes

2021-11-09 07:13 UTC, hfxsd commented on zh/open-api.md
>  DM 提供 OpenAPI 功能，用户可通过 OpenAPI 对 DM 集群进行查询和运维操作。OpenAPI 的总体功能和 [dmctl 工具](./dmctl-introduction.md)类似。如需开启该功能，请在 dm-master 的配置文件中增加如下配置项：
```suggestion
DM 提供 OpenAPI 功能，你可以通过 OpenAPI 对 DM 集群进行查询和运维操作。OpenAPI 的总体功能和 [dmctl 工具](./dmctl-introduction.md)类似。如需开启该功能，请在 dm-master 的配置文件中增加如下配置项：
```

2021-11-09 07:13 UTC, hfxsd commented
LGTM

2021-11-09 07:14 UTC, hfxsd approved these changes

2021-11-09 07:26 UTC, TomShawn approved these changes

2021-11-09 09:36 UTC, Ehco1996 commented
/hold

2021-11-09 09:39 UTC, Ehco1996 commented on en/open-api.md
> +> - The listening port of the DM-master node is 8216 by default. After you deploy the DM-master nodes, you can access `http://{host}:{port}/api/v1/docs` to preview the documentation online.
yes... 8261 is not default port.. it;s just the default port in our test-case😂😂😂, i will add some suggestion to fix this

2021-11-09 09:43 UTC, Ehco1996 requested changes

2021-11-09 09:43 UTC, Ehco1996 commented on en/open-api.md
> +> - The listening port of the DM-master node is 8216 by default. After you deploy the DM-master nodes, you can access `http://{host}:{port}/api/v1/docs` to preview the documentation online.
```suggestion
> - After you deploy the DM-master nodes, you can access `http://{master-addr}/api/v1/docs` to preview the documentation online.
```

it's my bad, please apply this change to docs-zh 😬😬😬😬

2021-11-11 08:26 UTC, Liuxiaozhen12 commented on en/open-api.md
> +> - The listening port of the DM-master node is 8216 by default. After you deploy the DM-master nodes, you can access `http://{host}:{port}/api/v1/docs` to preview the documentation online.
fixed in https://github.com/pingcap/docs-dm/pull/822/commits/aa04eeaf2b89de9939a401342a46783385ab405b. PTAL~

2021-11-12 01:12 UTC, Ehco1996 approved these changes

2021-11-12 02:46 UTC, Liuxiaozhen12 commented
/remove-status LGT1
/status LGT2

2021-11-12 02:47 UTC, Liuxiaozhen12 commented
/merge

2021-11-12 02:49 UTC, merged